name: redsocial
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Ajustado para compatibilidad con las librerías actuales
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos de estilo iOS
  cupertino_icons: ^1.0.8

  # Gestión de estado
  provider: ^6.1.0

  # Navegación
  go_router: ^14.0.0

  # Peticiones HTTP
  http: ^1.1.0

  # Variables de entorno
  flutter_dotenv: ^5.1.0

  # Previsualización en varios dispositivos
  device_preview: ^1.1.0

  # Formato de fechas (ej: "hace 5 minutos")
  timeago: ^3.6.1

  # Comparación de objetos
  equatable: ^2.0.5

  # Almacenamiento local (Token)
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- AQUÍ ESTABA EL ERROR DEL .ENV ---
  # Debes declarar explícitamente el archivo para que Flutter lo incl